apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-admin
rules:
- apiGroups: ["iam.cnrm.cloud.google.com"]
  resources: ["iamserviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummy-sa-sa-admin
  namespace: ama-api-main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sa-admin
subjects:
- kind: User
  name: iam-dummy-test-sa@ama-spi-main.iam.gserviceaccount.com