apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iam-admin-cluster
rules:
- apiGroups: ["iam.cnrm.cloud.google.com"]
  resources: ["iampolicies", "iampolicymembers", "iamserviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iam-admin-ns-role
  namespace: ama-spi-main
rules:
- apiGroups: ["iam.cnrm.cloud.google.com"]
  resources: ["iampolicies", "iampolicymembers", "iamserviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
    label-one: "value-one"
  name: iamserviceaccount-sample
spec:
  displayName: Example Service Account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spi-iam-main-iam-admin-cluster
  namespace: ama-spi-main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iam-admin-cluster
subjects:
- kind: User
  name: spi-iam-main@ama-spi-main.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spi-iam-main-iam-admin-cluster-ns
  namespace: ama-spi-main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iam-admin-ns-role
subjects:
- kind: User
  name: spi-iam-main@ama-spi-main.iam.gserviceaccount.com